name: API Testing Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  running-automation-test:
    runs-on: ubuntu-latest
    # download repo
    steps:
      - uses: actions/checkout@v4

      # setup java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # setup gradlew
      - name: Setup gradlew
        run: chmod +x gradlew

      # execute gradle command for running cucumber api test
      - name: Execute api test
        run: ./gradlew apiTest

      # archive api test result
      - name: Archive api test result
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: Cucumber API Test Report
          path: reports

      # deploy to github page
      - name: Deploy report to github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN_PAGES_GITHUB }}
          PUBLISH_DIR: reports
